### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by tanvlt** [ikzelf/zbxora#10]
Dear Sir, im trying to use zbxORA with Python2.7, but when i run test command: /usr/local/bin/python2.7 bin/zbxora.py -c etc/zbxora.fsdb02.cfg, i have a problem :

_[root@zabbix-test zbxora]# /usr/local/bin/python2.7 bin/zbxora.py -c etc/zbxora.fsdb02.cfg
2016-10-18 16:42:13 start zbxora-1.02 pid=35030 Connecting for hostname dbora...
2016-10-18 16:42:13.028231 site_checks: sap,ebs
2016-10-18 16:42:13.028258 to_zabbix_method: zabbix_sender /usr/local/bin/zabbix_sender -z 127.0.0.1 -T -i /root/zbxora_out/zbxora.fsdb02.zbx
2016-10-18 16:42:13.028280 out_file:/root/zbxora_out/zbxora.fsdb02.zbx
Traceback (most recent call last):
  File "bin/zbxora.py", line 183, in <module>
    if ITYPE == "RDBMS":
NameError: name 'ITYPE' is not defined_

Connection from zabbix server to DB server is good. Pls help me,
 and my config like:

_[zbxora]
db_url: //192.168.1.56:1521/dbora
username: zabbix
password: zabbix
role: normal
#####for ASM instance role should be SYSDBA
out_dir: $HOME/zbxora_out
hostname: dbora
checks_dir: etc/zbxora_checks
site_checks: sap,ebs
to_zabbix_method:  zabbix_sender
####if to_zabbix_method is zabbix_sender, every cycle a sender process is started
to_zabbix_args: /usr/local/bin/zabbix_sender -z 127.0.0.1 -T -i
####the output filename is added to to_zabbix_args_

**Comment by ikzelf** [comment]
Hi, first, stop using root to run zbxora.
Next, can you connect to your database using sqlplus ? zbxora does need the similar environment setup as sqlplus needs.
Does you zabbix database user have the correct privs inside the database?

grant create session, select any dictionary, oem_monitor to zabbix;
It looks like your zabbix user can not run this query:
select substr(i.version,0,instr(i.version,'.')-1),
                    s.sid, s.serial#, p.value instance_type, i.instance_name
                    , s.username
                    from v$instance i, v$session s, v$parameter p
                    where s.sid = (select sid from v$mystat where rownum = 1)
                    and p.name = 'instance_type';
test this using your zabbix database account using sqlplus. And yes, this should be better handled by zbxora.py, to raise an exception for that. I will fix the code, if you verified my assumption. What sql error do you get?

**Comment by tanvlt** [comment]
Dear, you was right, this is the incorrect privs, affter add "**_grant create session, select any dictionary, oem_monitor to zabbix;"_** and run querry test: 
[http://prnt.sc/cw327d](url)
I think connection DB well.
When i run zbxora again (with user zabbix), some error apear:

> 2016-10-19 10:28:38.279553	ebs_startup run at connect only
2016-10-19 10:28:38.279719		ebs.bagger: select * from gg
2016-10-19 10:28:39.069421 key=ebs_10m.ebs.concmgr ORA-942: Database execution error: ORA-00942: table or view does not exist
2016-10-19 10:28:39.071182 key=ebs_10m.ebs.paul.truncatp ORA-942: Database execution error: ORA-00942: table or view does not exist
2016-10-19 10:28:39.073475 key=ebs_60m.concmanager ORA-942: Database execution error: ORA-00942: table or view does not exist
2016-10-19 10:28:39.075677 key=ebs_discovery_60m.ebs.concmanager ORA-942: Database execution error: ORA-00942: table or view does not exist
2016-10-19 10:28:39.082434 key=ebs_startup.ebs.bagger ORA-942: Database execution error: ORA-00942: table or view does not exist
2016-10-19 10:28:39.085096 connect 1 times, 0 fail; started 37 queries, 5 fail memrss:25080 user:0.135979 sys:0.038994

Finaly, i dont know, how to run zbxora with template zbxORA. I have tried add host with Agent Interafce=127.0.0.1 and add template zbxORA while running zbxora; but dont work. Sr about that, i just a newbe in zabbix.

**Comment by ikzelf** [comment]
you have site_checks: sap, ebs in your config. This is just meant as an example. It means that zbxora will also load the sql's that are in sap.cfg and ebs.cfg where SAP application specific tables can be queries and where EBS specific queries van be included in you zabbix monitoring.
The zbxora process is running just fine now, it did 37 queries and 5 failed. In this case it were the queries that came from ebs.
You just need to import the zbxora template, create a host dbora (as you have in your zbxora config in the hostname parameter and attach the zbxora template to that host. Interfaces are of no importance for this host.
In your case, it might be easier to clear the site_checks parameter and restart zbxora. zbxora normally writes 1 log line/hour, reporting a few statistics about it's own execution.
If everything is working ok, you should see data appearing in your zabbix host using the Latest Data screen.
What version of zabbix are you using?

**Comment by tanvlt** [comment]
Dear, im using Zabbix 2.4.6, i restarted zbxora and still have 5 failed same above.
But i think, it is working  fine now and i can see some data in the Latest Data screen.
[http://prnt.sc/cw4twg](url)
And i hope zbxora can discover ASM-dgroups because im using Oracle Cluster with ASM.
Thank you very much!

**Comment by ikzelf** [comment]
Since you are using zabbix < 3, you should manually create the value mappings since there are not created for you during import of the template. If you want to monitor ASM diskgroups, you should connect to an ASM service. For this your zabbix user needs to have sysdba privs in the ASM instance, which is read only in ASM.
I am glad you got things working now.
If I were you, I would certainly upgrade to zabbix 3, if possible.

**Comment by tanvlt** [comment]
Thanks for notice, I had created the value mappings manually, and my plan upgrade to zabbix 3 in near future.
Now i'll try to test with ASM.
Thanks agian.

**Comment by ikzelf** [comment]
looks like closed now.
