### ISSUE TITLE
A little bit of precaution

### ISSUE THREAD

**Issue by dutrajulio** [ikzelf/zbxora#11]
Hi, thank you for your great job.

I mistakely run zbxora_sender without arguments, and it tried to move "/*" to "/home/zbxora/in". If anyone do this with root permissions then that person will be in a bad situation. I suggest you add an "if" as a "security measure".

if [ x$ZBXORA_OUT != x ]
then
        mv $ZBXORA_OUT/* $HOME/$ME/in
        cd $HOME/$ME/in

**Comment by ikzelf** [comment]
Thanks for your suggestion .... as a matter of fact, I already had this ready and just pushed the changes. And believe it or not ..... someone did run this as root ....

**Comment by ikzelf** [comment]
Thanks for your suggestion .... as a matter of fact, I already had this ready and just pushed the changes. And believe it or not ..... someone did run this as root ....

**Comment by ikzelf** [comment]
Thanks for your suggestion .... as a matter of fact, I already had this ready and just pushed the changes. And believe it or not ..... someone did run this as root ....

**Comment by ikzelf** [comment]
Thanks for your suggestion .... as a matter of fact, I already had this ready and just pushed the changes. And believe it or not ..... someone did run this as root ....
