### ISSUE TITLE
zbxora error

### ISSUE THREAD

**Issue by CGO00** [ikzelf/zbxora#13]
Hello,

I'm stuck with this error after launching the following command : `$HOME/ciber/bin/zbxora.py -c $HOME/ciber/etc/zbxora_checks/oracle/oracle_237.cfg`

`
Traceback (most recent call last):
  File "/root/ciber/bin/zbxora.py", line 84, in <module>
    DB_URL = CONFIG.get(ME[0], "db_url")
  File "/usr/lib64/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'zbxora'
`

Any idea ?

**Comment by ikzelf** [comment]
Ok, the idea of the config file you give with -c to zbxora.py is that this contains the connect information. I normally store them in $HOME/ciber/etc/ where you also find the zbxora_checks directory. In the download you will see an example named fsdb02.cfg. You will have to create a similar cfg file for every database that you want to monitor. The files in the zbxora_checks directory are found by zbxora.py based on the version of the database, the role in plays and the instance_type.
If you want extra metrics, there you can add site specific checks files, or edit the files from the download. The main error you hit is the fact that you config file has no [zbxora] section.
I hope this helps, feel free to ask for more clarifications.

**Comment by CGO00** [comment]
Hi Ikzelf,

My bad, i copy paste the wrong execution code.

I also encounter another issue in with the cfg file in "$HOME/ciber/etc/zbxora_checks/oracle/" called by "site_checks"

I don't have the error message anymore, but it says that the "$HOME/ciber/etc/zbxora_checks/oracle/my_cfg.cfg" was not found.

I solved the issue in "$HOME/ciber/etc/zbxora.db_name.cfg" by modifying the line "checks_dir" as in my cfg file i called it with "$HOME/ciber/etc/zbxora_checks" but you need to change "$HOME" by (in my case) "/root". I don't know why my home was not recognized as "$HOME" in my terminal was the right one.
