### ISSUE TITLE
Blocked Sessions

### ISSUE THREAD

**Issue by israellsantos** [ikzelf/zbxora#15]
Hi.

I'm setting up zbxora to monitor my databases.

I want to be able to monitor all blocked sessions. I've noticed a query on the primary.12.cfg check called "blocked" that do this, but there is no item mapped to receive this value on the template.

Do I need to create this item manually? Couldn't this be included on the zbxora template?

Thanks!

**Comment by ikzelf** [comment]
Hi,
yes, I could add this to the template but it is also very easy to do this yourself. See [http://ronr.blogspot.nl/2015/10/how-to-create-new-metrics-for-zbxora.html](url) for how to add new items. I wrote zbxora with simplicity and extensibility in mind. Go and give it a try.
