### ISSUE TITLE
zabbix 4.0 compatibility

### ISSUE THREAD

**Issue by starlessboi** [ikzelf/zbxora#18]
Hi
Is this scripts and template compatible to Zabbix 4 branch?
is there any template that is exported from Zabbix 4
thanks for your job

**Comment by ikzelf** [comment]
Hi,
yes, zbxdb is  compatible with any version of zabbix that I know of.
I currently use zabbix-v4 and just put a template in GitHub.
If  you see any possible improvements, please shout and/or contribute.
