### ISSUE TITLE
I can't import this templates to zabbix 2.4.6

### ISSUE THREAD

**Issue by kylexlau** [ikzelf/zbxora#2]
The error message is:

Cannot find value map "zbxora[connect,status]" used for item "zbxora[connect,status]" on "template zbxORA".

**Comment by ikzelf** [comment]
Hmm, could be my fault ….
Is there a special way to export those value maps?

**Comment by ikzelf** [comment]
For now, only thing I can find is to give this in text:

 <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=10&sid=fd734d4b0903783d>	1 ⇒ Up
zbxora arl_dest <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=24&sid=fd734d4b0903783d>	0 ⇒ OK
1 ⇒ DEFERRED
2 ⇒ ERROR
3 ⇒ UNK
zbxora rman status <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=23&sid=fd734d4b0903783d>	0 ⇒ COMPLETED
1 ⇒ FAILED
2 ⇒ COMPLETED WITH WARNINGS
3 ⇒ COMPLETED WITH ERRORS
4 ⇒ noinfo
5 ⇒ RUNNING
9 ⇒ unk
zbxora[checks,status] <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=21&sid=fd734d4b0903783d>	0 ⇒ OK
11 ⇒ unreadable
13 ⇒ parse error[s]
zbxora[connect,status] <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=19&sid=fd734d4b0903783d>	0 ⇒ OK
zbxora[query,,,status] <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=20&sid=fd734d4b0903783d>	0 ⇒ OK

**Comment by kylexlau** [comment]
Which zabbix version do you use to export this template?  It should be zabbix's fault.

**Comment by ikzelf** [comment]
it’s 2.4
I already found that there is something implemented in v3 for this.
I also found other templates with the same problem so I adjusted the README.md for this.
Did you get it running now?

Ronald.

**Comment by kylexlau** [comment]
I have created all the value mappings you give.  But the template depends on more value maps.

The error message:
Cannot find value map "db.openstatus" used for item prototype "{#PDB} openstatus" of discovery rule "dbnames" on "templatez bxORA"

**Comment by ikzelf** [comment]
sorry, I forgot to prefix them all:
zbxora db.openstatus <https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=18&sid=fd734d4b0903783d>	0 ⇒ *unknown*
1 ⇒ MOUNTED
2 ⇒ READ ONLY
3 ⇒ READ WRITE
4 ⇒ READ ONLY WITH APPLY

Just exported the template again, synced to repo. Thanks for the feedback.

Ronald.

**Comment by kylexlau** [comment]
Thanks for your support.  I have imported it successfully.

**Comment by ikzelf** [comment]
If you have any suggestions: please.

Groeten,
Ronald Rood

> Op 7 nov. 2015 om 17:35 heeft kylexlau <notifications@github.com> het volgende geschreven:
> 
> Thanks for your support. I have imported it successfully.
> 
> On Sat, Nov 7, 2015 at 11:26 PM, Ronald Rood <notifications@github.com>
> wrote:
> 
> > sorry, I forgot to prefix them all:
> > zbxora db.openstatus <
> > https://cbr-parc-001.nl.ciber.com/zabbix/adm.valuemapping.php?form=update&valuemapid=18&sid=fd734d4b0903783d>
> > 0 ⇒ *unknown*
> > 1 ⇒ MOUNTED
> > 2 ⇒ READ ONLY
> > 3 ⇒ READ WRITE
> > 4 ⇒ READ ONLY WITH APPLY
> >
> > Just exported the template again, synced to repo. Thanks for the feedback.
> >
> > Ronald.
> >
> >

**Comment by ev0lvr** [comment]
Wondering if you are planning on adding updated templates for 3.0 and above?  :)

**Comment by ev0lvr** [comment]
Wondering if you are planning on adding updated templates for 3.0 and above?  :)
