### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OrderedDict'

### ISSUE THREAD

**Issue by kanil4** [ikzelf/zbxora#5]
As per some comments from Google - seems like attribute 'OrderedDict' was only defined in python 2.7. I am running python 2.6.6 on my machine. 

Any help here will be appreciated.

**Comment by ikzelf** [comment]
What I did in a similar case was http://ronr.blogspot.nl/2015/09/install-python-without-root-access-to.html?m=1
Install a private python version.

Groeten,
Ronald Rood

**Comment by ikzelf** [comment]
Where you able to install a private python version?
