### ISSUE TITLE
zbxora_sender is dangerous

### ISSUE THREAD

**Issue by Bran-Ko** [ikzelf/zbxora#9]
I try to run zbxora_sender from bash. But I run it as root from its directory /usr/local/bin/zbxora_sender 
the only thing what I see was..
mv: cannot move /dev to /root/zbxora_sender/in/dev: Device or resource busy
mv: cannot move /opt to /root/zbxora_sender/in/opt: Device or resource busy
mv: cannot move /proc to /root/zbxora_sender/in/proc: Device or resource busy
mv: cannot move /root to a subdirectory of itself, /root/zbxora_sender/in/root
mv: cannot move /run to /root/zbxora_sender/in/run: Device or resource busy
mv: cannot move /sys to /root/zbxora_sender/in/sys: Device or resource busy
mv: cannot move /tmp to /root/zbxora_sender/in/tmp: Device or resource busy
/usr/local/bin/zbxora_sender: line 28: /root/log/zbxora_sender.Mon.log: No such file or directory
/usr/local/bin/zbxora_sender: line 29: find: command not found
/usr/local/bin/zbxora_sender: line 29: xargs: command not found
/usr/local/bin/zbxora_sender: line 30: find: command not found

I think that you know what happend next ... 
It will be much more better, if in initialize part of zbxora_sender will be check for arguments. Because server will be unresponsible (whole system dirs are moved to /root/zbxora_sender/in

**Comment by ikzelf** [comment]
oops ...... never run anything using root when not needed..... would be a good start but you are right, I will add some sanity checking into the sender tool but please, stop using root when you can really use low privileged accounts. Nothing in zbxora requires other than regular client privileges, as long as it can run bash, python and the oracle client it is ok. zbxora also needs write privileges in it's home directory....

**Comment by Bran-Ko** [comment]
Yes I know that root account is for another purposes. I seen that zbxora_sender has some arguments. I run it without argument to see usage :)
